# Generated by Django 3.2.6 on 2021-09-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20210904_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=50),
        ),
    ]
