# Generated by Django 3.2.6 on 2021-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20210830_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.TextField(blank=True, default=''),
        ),
    ]
